version: '3.1'

services:
  db:
    image: mysql
    ports:
    - 6000:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
    - C:\Programming\JavaDb\first\db:/var/lib/mysql

  adminer:
    image: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
