version: '3.1'

services:
  db:
    image: mysql
    ports:
    - 5999:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
    - C:\Programming\JavaDb\lab3\db:/var/lib/mysql

  adminer:
    image: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8085:80
